name: Gdp
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      -
        name: Setup
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dollazjerry
          password: SapuLidi10
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dollazjerry/maniax:latest



